import type { AssessmentState, ComplianceMapping, Finding } from "../findings/types.js";
import { severityOrder } from "../findings/types.js";

const esc = (value: string | undefined): string => value?.trim() || "Not provided";

const findingSection = (finding: Finding): string => {
  const evidence = finding.evidence.length
    ? finding.evidence
        .map((entry) => `- ${entry.id}: ${entry.title}${entry.path ? ` (${entry.path})` : ""}`)
        .join("\n")
    : "- No attached evidence";

  return [
    `### ${finding.id}: ${finding.title}`,
    "",
    `- Severity: ${finding.severity}`,
    `- Confidence: ${finding.confidence ?? "medium"}`,
    `- Target: ${finding.target}`,
    `- CWE: ${finding.cweIds.length ? finding.cweIds.join(", ") : "Not mapped"}`,
    `- CVE: ${finding.cveIds.length ? finding.cveIds.join(", ") : "Not mapped"}`,
    `- OWASP: ${finding.owaspCategory ?? "Not mapped"}`,
    "",
    "**Description**",
    "",
    esc(finding.description),
    "",
    "**Impact**",
    "",
    esc(finding.impact),
    "",
    "**Remediation**",
    "",
    esc(finding.remediation),
    "",
    "**Evidence**",
    "",
    evidence,
  ].join("\n");
};

const complianceSection = (mappings: ComplianceMapping[]): string => {
  if (!mappings.length) return "No compliance readiness mapping was generated.";
  return mappings
    .map((entry) =>
      [
        `- ${entry.framework} ${entry.controlId} - ${entry.title}`,
        `  - Status: ${entry.status}`,
        `  - Findings: ${entry.findingIds.length ? entry.findingIds.join(", ") : "none"}`,
        `  - Rationale: ${entry.rationale}`,
      ].join("\n"),
    )
    .join("\n");
};

export const renderMarkdownReport = (state: AssessmentState): string => {
  const findings = [...state.findings].sort(
    (left, right) => severityOrder[right.severity] - severityOrder[left.severity],
  );
  const findingText = findings.length
    ? findings.map(findingSection).join("\n\n")
    : "No findings were reported by this run.";
  const notes = state.notes.length
    ? state.notes.map((note) => `- ${note.title}: ${note.content.replace(/\s+/g, " ").slice(0, 240)}`).join("\n")
    : "- No notes";

  return [
    "# Null CLI Assessment Report",
    "",
    "> This report is generated by the open-source Null CLI agent. It is a scoped security assessment artifact and not a compliance certification.",
    "",
    "## Scope",
    "",
    `- Target: ${state.target}`,
    `- Goal: ${state.goal}`,
    `- Started: ${state.startedAt}`,
    `- Finished: ${state.finishedAt ?? "Not finished"}`,
    "",
    "## Executive Summary",
    "",
    `${findings.length} finding(s) reported. Highest severity: ${findings[0]?.severity ?? "none"}.`,
    "",
    "## Findings",
    "",
    findingText,
    "",
    "## Compliance Readiness Mapping",
    "",
    complianceSection(state.complianceMappings),
    "",
    "## Notes",
    "",
    notes,
    "",
  ].join("\n");
};
